spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/expert
    password: '12345678'
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  application:
    name: expert
jwt:
    secret: ${jwt.secret.key}
    expirationMs: 86400000
